### ISSUE TITLE
An issue with - in names?

### ISSUE THREAD

**Issue by Folcon** [binaryage/dirac-sample#2]
This may be a new bug, but testing this out today, I came across this issue.

<img width="596" alt="screen shot 2017-01-24 at 00 02 41" src="https://cloud.githubusercontent.com/assets/123055/22228365/91e8c92e-e1c8-11e6-83bf-0891966ef896.png">

I'm using the repo provided, some debug data incase it's helpful.

```
Installing CLJS DevTools 0.9.0 and enabling features :formatters :hints :async
Installing Dirac Runtime 1.1.0 and enabling features :repl
tag: binaryage/dirac-sample | http://localhost:9977/demo.html | Chrome/58.0.2990.0 | Mac/10.11.6

Your current nREPL session is a Dirac session (ClojureScript) connected to 'binaryage/dirac-sample | http://localhost:9977/demo.html | Chrome/58.0.2990.0 | Mac/10.11.6 [74b1ea3e]'
with selected ClojureScript compiler nil (any available) which is currently matching compiler <dirac/74b1ea3e.1>.
```

If you need any additional info please ask.

**Comment by darwin** [comment]
Ah, you are right. I broke it in this commit:
https://github.com/binaryage/dirac/commit/1cba5e972048e3732e59318892a9a9ddcee5f286

That regexp must be more specific.

**Comment by Folcon** [comment]
I'm glad you caught it :)...
