### ISSUE TITLE
Cannot read property ('_script' of null | 'element' of undefined)

### ISSUE THREAD

**Issue by onetom** [binaryage/dirac-sample#3]
I'm getting these errors after I open the Dirac window:
```
Internal Dirac Error TypeError: Cannot read property '_script' of null
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined



Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property 'element' of undefined
Internal Dirac Error TypeError: Cannot read property '_script' of null
Internal Dirac Error TypeError: Cannot read property '_script' of null
Internal Dirac Error TypeError: Cannot read property '_script' of null
```

Chrome: Version 60.0.3076.0 (Official Build) canary (64-bit)

Regular dev tools console:
```
util.cljs:186 Installing CLJS DevTools 0.9.3 and enabling features :formatters :hints :async
util.cljs:95 Installing Dirac Runtime 1.2.4 and enabling features :repl
core.cljs:163 tag: binaryage/dirac-sample | http://localhost:9977/demo.html | Chrome/60.0.3076.0 | Mac/10.12.4
demo.cljs:44 demo loaded
demo.cljs:27 calling breakpoint-demo:
core.cljs:163 number 0 is even
core.cljs:163 number 1 is odd
core.cljs:163 number 2 is even
```

How can I debug it further?

Is it reproducible for others too?

**Comment by onetom** [comment]
I tried an other project on Chrome Version 60.0.3075.0 (Official Build) canary (64-bit) and it was still working. Since chrome updates automatically I didn't have the chance to try this `dirac-sample` app, but it's highly likely it would have also worked. So it smells like a chrome regression.

**Comment by darwin** [comment]
Confirmed. For now... you can work around it by disabling “Use backend-supported API & CSS” in Dirac Extension Options.

[chrome://extensions/?options=kbkdngfljkchidcjpnfcgcokkbhlkogi]()

It will still spit some error, but it seems to work, at least REPL.

From our Slack discussion:

```
[14:27] 
darwin interesting enough this problem is only reproducible on 60.0.3076.0/Mac on Linux it works

[14:27] 
this is some kind of mis-match of the debugger protocol API, Mac version does not provide some functions which should be there

[14:42]
darwin ok, for some reason they renamed “Rendering” group of protocol APIs to “Overlay”, but this is not reflected in latest devtools sources and even not in chromium master. It smells like some private changes which got into 3076/Mac.
```

**Comment by darwin** [comment]
I looked at the commit history and now it is more clear.

The new functionality got [committed](https://chromium.googlesource.com/chromium/src/+/8982f602a8e1f521949d8dd8dae58cff1c787bec) but later [reverted](https://chromium.googlesource.com/chromium/src/+/2b40e81c40d0ca831ac5206de0547a70d316f310). And later again [committed](https://chromium.googlesource.com/chromium/src/+/7afbb9a64fbd30254a2dab9a689648621fa29f14) and [reverted](https://chromium.googlesource.com/chromium/src/+/e4c132b04e4a9b43b9d8db37f0ef7895c53d4fb5). So the Mac build was created before the revert when the codebase was in flux. The Linux build stayed consistent.

This issue will go away in the next release. Maybe I will have to cut a new Dirac release.

**Comment by darwin** [comment]
Canary 60.0.3077.0/Mac works again.

**Comment by darwin** [comment]
Canary 60.0.3078.0/Mac landed the change again, so it does not work with 1.2.4 anymore. 

Use [v1.2.5](https://github.com/binaryage/dirac/releases/tag/v1.2.5) instead.
